- name: "Installing software for 'jenkins-training-master'"
  yum: pkg={{ item }} state=installed
  with_items:
    - java-1.8.0-openjdk
  notify:
    - curl config files
    - jenkins-ci key
    - install jenkins
    - start jenkins
    - execute cat jenkins secrets
    - reboot server
