- hosts: all
  become: true
  roles:
    - basic

- hosts: jenkins-training-master
  become: true
  roles:
    - jenkins-master

- hosts: jenkins-training-slave
  become: true
  roles:
    - jenkins-slave
