- name: curl config files
  get_url:
    url: http://pkg.jenkins-ci.org/redhat-stable/jenkins.repo
    dest: /etc/yum.repos.d/jenkins.repo

- name: jenkins-ci key
  rpm_key:
    key: https://jenkins-ci.org/redhat/jenkins-ci.org.key
    state: present

- name: install jenkins
  yum: pkg=jenkins-2.89.4 state=installed

- name: start jenkins
  service: name=jenkins state=started enabled=yes

- name: reboot server
  command: /sbin/shutdown -r +30
  async: 0
  poll: 0
  ignore_errors: true
